In [2]:
import numpy as np

# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [3]:
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [24]:
a = []
b = []

while len(a) < 5:
    a1 = int(input('enter number for list 1: '))
    a.append(a1)
while len(b) < 5:
    b1 = int(input('enter number for list 2: '))
    b.append(b1)
    
print('2 lists are \n',a, '\n', b)

a2 = np.array(a)
b2 = np.array(b)
print('2 arrays are \n',a2, '\n', b2)

c = np.concatenate((a2,b2), axis = 0)
print('concatenated array is ',c)
c.sort()
print('sorted concatenated array is ',c)

enter number for list 1: 10
enter number for list 1: 8
enter number for list 1: 6
enter number for list 1: 4
enter number for list 1: 2
enter number for list 2: 1
enter number for list 2: 3
enter number for list 2: 5
enter number for list 2: 7
enter number for list 2: 9
2 lists are 
 [10, 8, 6, 4, 2] 
 [1, 3, 5, 7, 9]
2 arrays are 
 [10  8  6  4  2] 
 [1 3 5 7 9]
concatenated array is  [10  8  6  4  2  1  3  5  7  9]
sorted concatenated array is  [ 1  2  3  4  5  6  7  8  9 10]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [44]:
a = np.arange(0,18).reshape(3,6)

In [49]:
print('shape of array is ',a.shape)
print('dimension of array is ',a.ndim)
print('size of array is ',a.size)

shape of array is  (3, 6)
dimension of array is  2
size of array is  18


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [56]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.expand_dims(a,0)
print('dimension of a ',a,' is ',a.ndim)
print('dimension of b ',b,' is ',b.ndim)

dimension of a  [ 1  2  3  4  5  6  7  8  9 10]  is  1
dimension of b  [[ 1  2  3  4  5  6  7  8  9 10]]  is  2


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [67]:
a = np.identity(4)
b = np.ones([4,4])
print('horizontal stacking \n',np.hstack([a,b]),'\n')
print('vertical stacking \n',np.vstack([a,b]))

horizontal stacking 
 [[1. 0. 0. 0. 1. 1. 1. 1.]
 [0. 1. 0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1.]] 

vertical stacking 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Questions 6:
How to get unique items and counts of unique items?

In [86]:
a = np.random.randint(20, size = (5,5))
print('array is ',a)
b = np.unique(a, return_counts= True)
c = np.vstack([b[0], b[1]])
print('unique values in the array and their correspoing frequencies are mentioned below \n',c)

array is  [[12 18 16 17  2]
 [10 13  9  7  0]
 [15 19 17  9  6]
 [ 9  9 13  7  4]
 [ 7  2 18  8  3]]
unique values in the array and their correspoing frequencies are mentioned below 
 [[ 0  2  3  4  6  7  8  9 10 12 13 15 16 17 18 19]
 [ 1  2  1  1  1  3  1  4  1  1  2  1  1  2  2  1]]
